FROM node:20-alpine
WORKDIR /app
RUN npm install -g pnpm
COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY packages/ packages/
COPY apps/scheduling-service/ apps/scheduling-service/
RUN pnpm install --frozen-lockfile
WORKDIR /app/apps/scheduling-service
CMD ["pnpm", "dev"]
